import type { Application, Candidate, Job, Interview, NotificationItem } from '../types';

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: 'app-01',
    jobId: 'job-01',
    jobTitle: 'Senior Full Stack Engineer',
    company: 'CloudScale AI',
    location: 'San Francisco, CA (Remote)',
    appliedDate: 'Sep 08, 2026',
    status: 'Interview',
    aiMatchScore: 94,
    matchTier: 'excellent',
    salary: '$160k - $190k',
    workType: 'Remote',
    notes: 'Technical round scheduled for tomorrow at 2:30 PM with Lead Architect.',
  },
  {
    id: 'app-02',
    jobId: 'job-02',
    jobTitle: 'Frontend Platform Architect',
    company: 'Veloce Data Systems',
    location: 'New York, NY (Hybrid)',
    appliedDate: 'Sep 05, 2026',
    status: 'Shortlisted',
    aiMatchScore: 91,
    matchTier: 'excellent',
    salary: '$175k - $210k',
    workType: 'Hybrid',
    notes: 'Resume passed ATS AI screening. Recruiter screening completed.',
  },
  {
    id: 'app-03',
    jobId: 'job-03',
    jobTitle: 'Staff React / TypeScript Engineer',
    company: 'Aether Health',
    location: 'Austin, TX (Remote)',
    appliedDate: 'Aug 29, 2026',
    status: 'Screening',
    aiMatchScore: 88,
    matchTier: 'strong',
    salary: '$165k - $195k',
    workType: 'Remote',
    notes: 'Under initial algorithmic parsing and qualification check.',
  },
  {
    id: 'app-04',
    jobId: 'job-04',
    jobTitle: 'Senior Python & React Developer',
    company: 'Krypton Labs',
    location: 'Seattle, WA (Remote)',
    appliedDate: 'Aug 22, 2026',
    status: 'Applied',
    aiMatchScore: 82,
    matchTier: 'strong',
    salary: '$150k - $180k',
    workType: 'Remote',
  },
  {
    id: 'app-05',
    jobId: 'job-05',
    jobTitle: 'Full Stack AI Solutions Engineer',
    company: 'Synthetix Systems',
    location: 'Boston, MA (Hybrid)',
    appliedDate: 'Aug 14, 2026',
    status: 'Under Review',
    aiMatchScore: 78,
    matchTier: 'good',
    salary: '$155k - $185k',
    workType: 'Hybrid',
  },
];

export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: 'cand-01',
    name: 'Rahul Kumar',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    initials: 'RK',
    title: 'Senior Full Stack Developer',
    email: 'rahul.kumar@resumio.ai',
    phone: '+91 98765 43210',
    location: 'Bangalore, India (Open to Remote)',
    experienceYears: 6.5,
    aiScore: 94,
    matchTier: 'excellent',
    status: 'Shortlisted',
    appliedJob: 'Senior Full Stack Engineer',
    appliedDate: 'Sep 08, 2026',
    education: 'B.Tech in Computer Science, IIT Madras',
    salaryExpectation: '$160k - $185k',
    resumeFileName: 'Rahul_Kumar_Resume_2026.pdf',
    summary:
      'Full Stack Engineer with 6+ years specializing in TypeScript, React, Next.js, Node.js, and high-throughput distributed systems. Built real-time collaborative workspaces serving 250k+ daily active users.',
    skills: [
      { name: 'TypeScript', match: true, level: 'Expert' },
      { name: 'React / Next.js', match: true, level: 'Expert' },
      { name: 'Node.js / Express', match: true, level: 'Expert' },
      { name: 'PostgreSQL', match: true, level: 'Proficient' },
      { name: 'Tailwind CSS', match: true, level: 'Expert' },
      { name: 'Docker / Kubernetes', match: true, level: 'Proficient' },
      { name: 'GraphQL', match: true, level: 'Proficient' },
      { name: 'AWS Cloud', match: true, level: 'Proficient' },
      { name: 'Rust', match: false, level: 'Familiar' },
    ],
    topStrengths: [
      'Exceptional React & state management architecture (98th percentile)',
      'Proven track record scaling API microservices to 10k RPS',
      'Strong open-source contributions & clean component design system skills',
    ],
    skillGaps: ['Rust / WebAssembly experience is at beginner level'],
  },
  {
    id: 'cand-02',
    name: 'Elena Rostova',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    initials: 'ER',
    title: 'Lead Frontend Engineer',
    email: 'elena.rostova@techmail.io',
    phone: '+1 (415) 555-0192',
    location: 'San Francisco, CA',
    experienceYears: 8,
    aiScore: 92,
    matchTier: 'excellent',
    status: 'Interview',
    appliedJob: 'Frontend Platform Architect',
    appliedDate: 'Sep 07, 2026',
    education: 'M.S. in Software Engineering, UC Berkeley',
    salaryExpectation: '$190k - $215k',
    resumeFileName: 'Elena_Rostova_CV.pdf',
    summary:
      'Frontend leader with deep domain mastery in micro-frontends, WebGL data visualization, and web performance optimization (sub-100ms LCP). Led a team of 12 engineers at FinTech scale.',
    skills: [
      { name: 'React', match: true, level: 'Expert' },
      { name: 'TypeScript', match: true, level: 'Expert' },
      { name: 'Design Systems', match: true, level: 'Expert' },
      { name: 'Performance Optimization', match: true, level: 'Expert' },
      { name: 'GraphQL', match: true, level: 'Proficient' },
      { name: 'CI/CD Pipelines', match: true, level: 'Proficient' },
    ],
    topStrengths: [
      'Reduced core bundle size by 48% across flagship SaaS web app',
      'Authored corporate-wide enterprise design system components',
    ],
    skillGaps: ['Backend Python experience is limited'],
  },
  {
    id: 'cand-03',
    name: 'Marcus Vance',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    initials: 'MV',
    title: 'Senior Backend & AI Engineer',
    email: 'm.vance@aiworks.org',
    phone: '+1 (206) 555-0144',
    location: 'Seattle, WA',
    experienceYears: 5,
    aiScore: 89,
    matchTier: 'strong',
    status: 'Screening',
    appliedJob: 'Senior Python & React Developer',
    appliedDate: 'Sep 06, 2026',
    education: 'B.S. in Computer Engineering, University of Washington',
    salaryExpectation: '$165k - $185k',
    resumeFileName: 'Marcus_Vance_Resume.pdf',
    summary:
      'Backend specialist experienced with Python, FastAPI, vector databases (Pinecone, Qdrant), and LLM orchestration (LangChain, LlamaIndex). Built retrieval augmented generation pipelines.',
    skills: [
      { name: 'Python / FastAPI', match: true, level: 'Expert' },
      { name: 'PostgreSQL / pgvector', match: true, level: 'Expert' },
      { name: 'Redis', match: true, level: 'Proficient' },
      { name: 'React', match: true, level: 'Proficient' },
      { name: 'Docker / K8s', match: true, level: 'Proficient' },
    ],
    topStrengths: ['Deep expertise in semantic search & embedding indexing architectures'],
    skillGaps: ['Advanced CSS/Animation expertise is moderate'],
  },
  {
    id: 'cand-04',
    name: 'Amara Chen',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    initials: 'AC',
    title: 'Full Stack Engineer (React/Go)',
    email: 'amara.chen@devhub.io',
    phone: '+1 (512) 555-0811',
    location: 'Austin, TX',
    experienceYears: 4,
    aiScore: 85,
    matchTier: 'strong',
    status: 'Under Review',
    appliedJob: 'Senior Full Stack Engineer',
    appliedDate: 'Sep 04, 2026',
    education: 'B.S. in CS, UT Austin',
    salaryExpectation: '$145k - $165k',
    resumeFileName: 'Amara_Chen_Resume.pdf',
    summary:
      'High-velocity product engineer comfortable jumping between frontend React/Tailwind interfaces and resilient Go microservices. Passionate about developer tooling.',
    skills: [
      { name: 'React', match: true, level: 'Expert' },
      { name: 'Golang', match: true, level: 'Proficient' },
      { name: 'TypeScript', match: true, level: 'Proficient' },
      { name: 'PostgreSQL', match: true, level: 'Proficient' },
    ],
    topStrengths: ['Rapid feature delivery and strong product-minded intuition'],
    skillGaps: ['Kubernetes cluster operations'],
  },
  {
    id: 'cand-05',
    name: 'David Kim',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    initials: 'DK',
    title: 'Staff Cloud & Infrastructure Engineer',
    email: 'david.kim@cloudsys.net',
    phone: '+1 (312) 555-0923',
    location: 'Chicago, IL',
    experienceYears: 9,
    aiScore: 78,
    matchTier: 'good',
    status: 'Applied',
    appliedJob: 'Full Stack AI Solutions Engineer',
    appliedDate: 'Aug 30, 2026',
    education: 'B.S. in Electrical Engineering, UIUC',
    salaryExpectation: '$180k - $200k',
    resumeFileName: 'David_Kim_CV_2026.pdf',
    summary:
      'DevOps and infrastructure specialist with extensive Terraform, AWS, multi-region cluster reliability, and security compliance experience.',
    skills: [
      { name: 'AWS / GCP', match: true, level: 'Expert' },
      { name: 'Terraform', match: true, level: 'Expert' },
      { name: 'Kubernetes', match: true, level: 'Expert' },
      { name: 'TypeScript', match: false, level: 'Familiar' },
    ],
    topStrengths: ['99.99% uptime architecture design for enterprise clients'],
    skillGaps: ['Frontend framework experience is limited'],
  },
];

export const MOCK_JOBS: Job[] = [
  {
    id: 'job-01',
    title: 'Senior Full Stack Engineer',
    department: 'Core Platform',
    company: 'CloudScale AI',
    location: 'San Francisco, CA',
    type: 'Full-time',
    workplace: 'Remote',
    experienceLevel: 'Senior',
    salaryRange: '$160,000 - $190,000',
    postedDate: '3 days ago',
    applicantsCount: 42,
    shortlistedCount: 8,
    status: 'Active',
    matchScoreForUser: 94,
    tags: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'AWS'],
    description:
      'We are looking for a Senior Full Stack Engineer to lead the development of our next-generation AI orchestration platform. You will architect responsive web clients and high-throughput backend services.',
    requiredSkills: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'AWS Cloud'],
  },
  {
    id: 'job-02',
    title: 'Frontend Platform Architect',
    department: 'Design & UX Platform',
    company: 'Veloce Data Systems',
    location: 'New York, NY',
    type: 'Full-time',
    workplace: 'Hybrid',
    experienceLevel: 'Lead',
    salaryRange: '$175,000 - $210,000',
    postedDate: '1 week ago',
    applicantsCount: 36,
    shortlistedCount: 6,
    status: 'Active',
    matchScoreForUser: 91,
    tags: ['React', 'Design Systems', 'Micro-frontends', 'Performance'],
    description:
      'Shape the frontend architecture powering our real-time analytics suite. Create high-performance component systems and guide architectural standards across 5 product teams.',
    requiredSkills: ['React', 'Design Systems', 'TypeScript', 'Web Performance'],
  },
  {
    id: 'job-03',
    title: 'Staff React / TypeScript Engineer',
    department: 'Patient Experience',
    company: 'Aether Health',
    location: 'Austin, TX',
    type: 'Full-time',
    workplace: 'Remote',
    experienceLevel: 'Senior',
    salaryRange: '$165,000 - $195,000',
    postedDate: '2 weeks ago',
    applicantsCount: 29,
    shortlistedCount: 5,
    status: 'Active',
    matchScoreForUser: 88,
    tags: ['Next.js', 'Tailwind CSS', 'GraphQL', 'Accessibility'],
    description:
      'Join our mission-driven engineering group to create empathetic, ultra-accessible healthcare interfaces utilized by millions of patients and medical practitioners daily.',
    requiredSkills: ['React', 'Next.js', 'TypeScript', 'GraphQL'],
  },
  {
    id: 'job-04',
    title: 'Senior Python & React Developer',
    department: 'Machine Learning Products',
    company: 'Krypton Labs',
    location: 'Seattle, WA',
    type: 'Full-time',
    workplace: 'Remote',
    experienceLevel: 'Senior',
    salaryRange: '$150,000 - $180,000',
    postedDate: '2 weeks ago',
    applicantsCount: 19,
    shortlistedCount: 4,
    status: 'Active',
    matchScoreForUser: 82,
    tags: ['Python', 'FastAPI', 'React', 'Vector DBs'],
    description:
      'Bridge the gap between state-of-the-art ML models and intuitive user applications. Develop high-speed asynchronous APIs and interactive data exploration dashboards.',
    requiredSkills: ['Python', 'FastAPI', 'React', 'Docker'],
  },
  {
    id: 'job-05',
    title: 'Full Stack AI Solutions Engineer',
    department: 'Applied AI Solutions',
    company: 'Synthetix Systems',
    location: 'Boston, MA',
    type: 'Full-time',
    workplace: 'Hybrid',
    experienceLevel: 'Mid',
    salaryRange: '$140,000 - $170,000',
    postedDate: '3 weeks ago',
    applicantsCount: 16,
    shortlistedCount: 5,
    status: 'Active',
    matchScoreForUser: 78,
    tags: ['TypeScript', 'LangChain', 'Python', 'React'],
    description:
      'Work directly with enterprise clients to customize, integrate, and deploy our proprietary document intelligence AI agents into their existing cloud workflows.',
    requiredSkills: ['TypeScript', 'Python', 'React', 'REST APIs'],
  },
];

export const MOCK_INTERVIEWS: Interview[] = [
  {
    id: 'int-01',
    candidateName: 'Rahul Kumar',
    candidateAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Senior Full Stack Engineer',
    date: '2026-09-11',
    time: '02:30 PM',
    duration: '45 mins',
    type: 'Technical Round',
    interviewer: 'David Martinez (Engineering Director)',
    meetLink: 'https://meet.google.com/xyz-qwer-abc',
    status: 'Upcoming',
  },
  {
    id: 'int-02',
    candidateName: 'Elena Rostova',
    candidateAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Frontend Platform Architect',
    date: '2026-09-14',
    time: '11:00 AM',
    duration: '60 mins',
    type: 'Hiring Manager',
    interviewer: 'Sarah Jenkins (Lead Recruiter)',
    meetLink: 'https://meet.google.com/uvw-mnop-def',
    status: 'Upcoming',
  },
  {
    id: 'int-03',
    candidateName: 'Marcus Vance',
    candidateAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Senior Python & React Developer',
    date: '2026-09-16',
    time: '04:00 PM',
    duration: '30 mins',
    type: 'AI Screening',
    interviewer: 'Resumio AI Assistant & Screening Agent',
    meetLink: 'https://resumio.ai/screen/ai-room-992',
    status: 'Upcoming',
  },
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-01',
    title: 'Welcome to Resumio',
    description: 'Your Phase 1 account has been successfully initialized in the SQLite database.',
    time: 'Just now',
    unread: true,
    type: 'system',
  },
  {
    id: 'notif-02',
    title: 'Profile Completion',
    description: 'Update your contact coordinates and bio to reach 100% profile strength.',
    time: '5 minutes ago',
    unread: true,
    type: 'system',
  },
  {
    id: 'notif-03',
    title: 'Security Verified',
    description: 'Your password is encrypted with industry-standard bcrypt hashing.',
    time: '1 hour ago',
    unread: false,
    type: 'system',
  },
];

export const MOCK_RECRUITER_FUNNEL = [
  { stage: 'Applied', count: 142, color: 'bg-slate-400', percentage: '100%' },
  { stage: 'Screening', count: 86, color: 'bg-amber-500', percentage: '60.5%' },
  { stage: 'Shortlisted', count: 28, color: 'bg-purple-500', percentage: '19.7%' },
  { stage: 'Interview', count: 14, color: 'bg-indigo-500', percentage: '9.8%' },
  { stage: 'Selected', count: 4, color: 'bg-emerald-500', percentage: '2.8%' },
];
